version: '3.5'
services:
  postgres:
    image: sorandom/hasura-postgres:latest
    restart: always
    logging:
          options:
            max-size: 10m
            max-file: "3"
    volumes:
      - pg_data:/var/lib/postgresql/data
  graphql-engine:
    image: sorandom/hasura-service:latest
    environment:
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL:  postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 10
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always

  node_server:
    image: sorandom/hasura-node:latest
    ports:
      - 3000:3000
    volumes:
      - ./:/hasura-starter

volumes:
  pg_data: