version: '3.5'
services:
  postgres:
    image: postgres:12
    restart: always
    logging:
          options:
            max-size: 10m
            max-file: "3"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.11.1.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 10
    volumes:
      - ./metadata:/hasura-metadata

  node_server:
    container_name: node_server
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["npm", "run", "prod"]
    ports:
      - 3000:3000
    volumes:
      - ./:/hasura-starter

volumes:
  db_data:
  pg_data: