version: '3.5'
services:
  postgres:
    image: sorandom/hasura-postgres:latest
    restart: always
    logging:
          options:
            max-size: 10m
            max-file: "3"
    volumes:
      - pg_data:/var/lib/postgresql/data
  graphql-engine:
    image: sorandom/hasura-starter
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always

  node_server:
    image: sorandom/hasura-node:latest
    ports:
      - 3000:3000
    volumes:
      - ./:/hasura-starter

volumes:
  pg_data: