name: hasura-starter
on:
  push: 
    branches: 
    - master
  pull_request: 
    branches:
    - master
jobs: 
  explore-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install

      - name: Start containers
        run: docker-compose up -d

      - name: Check containers
        run: docker ps

      - name: Stop containers
        if: always()
        run: docker-compose down
